apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: restaurant
data:
  DB_TYPE: "mongo"
  MONGO_URI: "mongodb://host.docker.internal:27017"
  MONGO_DB_NAME: "restaurant"
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "restaurant"
  KEYCLOAK_URL: "http://host.docker.internal:8080"
  KEYCLOAK_REALM: "restaurant-realm"
  KEYCLOAK_CLIENT_ID: "restaurant-api"
  REDIS_URL: "redis://host.docker.internal:6379"
  ELASTIC_URL: "http://host.docker.internal:9200"
  SEARCH_PORT: "3001"
  PORT: "3000"