apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: restaurant
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASSWORD: "admin"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  KEYCLOAK_CLIENT_SECRET: "vtKM5Zuios5Lrdp1bqKvt6P8cKT1OVjf"